version: '3.8'

services:
  app:
    container_name: auto-service
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
