version: '3.8'

services:
  app:
    container_name: vturb_service
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt  # Monta o volume do Certbot aqui
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt  # Monta o volume do Certbot aqui
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/lib/letsencrypt
      --email automacaosiberia@gmail.com
      --agree-tos
      --no-eff-email
      -d energyblessingsapp.com"

volumes:
  certbot-etc:
  certbot-var:
