ACTIVE_OFFERS_INFO = [
    {"offer_name": "PLR_ESP"},
    {"offer_name": "TSR_ESP"},
    {"offer_name": "LOV_ENG"},
    {"offer_name": "MSG_ESP"},
    {"offer_name": "TDB_ESP"},
    {"offer_name": "LVF_ESP"},
    {"offer_name": "TMP_ESP"},
    {"offer_name": "TIN_ESP"},
    {"offer_name": "FDA_ESP"},
    {"offer_name": "LVH_ESP"},
    {"offer_name": "SDA_ENG"},
    {"offer_name": "ECL_ESP"},
    {"offer_name": "TDF_ESP"},
    {"offer_name": "OBS_ESP"},
    {"offer_name": "CRC_ESP"},
    {"offer_name": "MAP_ESP"},
    {"offer_name": "MSG_ESP"},
    {"offer_name": "OPA_ESP"},
    {"offer_name": "OPA_ENG"},
    {"offer_name": "TNT_ENG"},
    {"offer_name": "BJC_ENG"},
    {"offer_name": "LOV_ESP"},
    {"offer_name": "HSA_ESP"},
]
